services:
  web:
    build: ./frontend  
    depends_on:
      backend:
        condition: service_healthy
    ports:
      - "3001:5173"
    networks:
      - app-network
    environment:
      VITE_API_URL: http://backend:3000/api

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    networks:
      - app-network

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - anime:/data/db
    networks:
      - app-network

    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  anime:

networks:
  app-network:
    driver: bridge